### ISSUE TITLE
[Vercel Speed Insights] Failed to load script from /_vercel/speed-insights/script.js.

### ISSUE THREAD

**Issue by justbenni** [zurlyy/zurly.me#1]
Hey, i have used your "Personal Website" and i got a error in my console. Please help me.
Error code: **[Vercel Speed Insights] Failed to load script from /_vercel/speed-insights/script.js. Please check if any content blockers are enabled and try again.**
![Screenshot 2024-02-11 171648](https://github.com/zurlyy/zurly.me/assets/123233187/90d5f05f-a82e-4190-9ae5-bdba939e14ff)

**Comment by dk-e** [comment]
Hey so as you're not hosting with vercel - rather your VPS, this functionality will not work. To stop this error you can navigate to the layout.tsx and remove the `<SpeedInsights />` component on line 16 😊.

**Comment by justbenni** [comment]
It works for me thankes 😀.
